import Link from "next/link";
import publications from "@/data/publications.json";
import { Arrow, Breadcrumbs, CtaBand, PageHero, SectionTitle, Status } from "./components";

export function PublicationsReworkedPage() {
  return <><Breadcrumbs items={[{ label: "Research", href: "/research" }, { label: "Publications" }]} /><PageHero eyebrow="PRA publications" title="Mechanisms, evidence, and limitations in the open." intro="The commercial site uses product language; these public research links provide the deeper mechanisms, experimental context, corrections, and negative results behind it." /><section className="section wrap"><div className="publication-list">{publications.map((paper) => <a href={paper.href} key={paper.title}><span>{paper.type}</span><div><h2>{paper.title}</h2><p>{paper.description}</p></div><Arrow /></a>)}</div></section><CtaBand title="Turn research evidence into a deployment decision." /></>;
}

export function AgentReworkedPage() {
  return <><Breadcrumbs items={[{ label: "PRA", href: "/products/pra" }, { label: "Agent" }]} /><PageHero eyebrow="PRA Agent · Reference application" title="Treat tasks, tools, results, sessions, and source records as first-class context." intro="PRA Agent is an optional reference surface for long-running work. PRA also fits existing agents through the Gateway and SDK, so adopting context selection does not require replacing the application loop." /><section className="engine-summary"><div className="wrap"><Status>In progress</Status><span>Open-source product direction</span></div></section><section className="section wrap"><SectionTitle eyebrow="Context model" title="Stop replaying the whole working set on every turn." /><div className="feature-cards"><article><span>01</span><h3>Sessions retain stable identity</h3></article><article><span>02</span><h3>Tasks define execution scope</h3></article><article><span>03</span><h3>Tools and results stay addressable</h3></article><article><span>04</span><h3>Exact source records remain recoverable</h3></article></div></section><section className="section section-tint"><div className="wrap two-column"><SectionTitle eyebrow="Compatibility" title="Use an existing agent or the reference surface." copy="Selected Context is ordinary text at the model boundary. Typed resources and qualified native integrations are optional upgrades with explicit fallback." /><div><ul className="check-list"><li>Gateway path for OpenAI-compatible applications</li><li>SDK path for direct record and selection control</li><li>Authorization remains independent of retrieval relevance</li><li>No raw native memory on the agent-facing wire</li></ul><p className="honesty-note">The public CLI reviewed for this site does not yet expose a generally available agent command. This page describes the product direction without presenting it as shipping.</p></div></div></section><CtaBand title="Bring PRA to the agent you already run." /></>;
}

const solutions = {
  "long-context": { eyebrow: "Long-context systems", title: "Keep the working set large without replaying it all.", intro: "Turn documents, history, tools, and task state into addressable resources and materialize only the selected detail.", points: ["Bound visible context", "Preserve exact source detail", "Measure quality against Full Context", "Choose text or native execution by evidence"] },
  "agent-infrastructure": { eyebrow: "Agent infrastructure", title: "Give agents durable context without an ever-growing prompt.", intro: "Represent sessions, tasks, tools, results, documents, and history as typed, scoped records that can be selected and recovered.", points: ["Typed records", "Task execution scope", "Authorization-aware selection", "Existing-agent compatibility"] },
  "inference-optimization": { eyebrow: "Inference optimization", title: "Optimize context as a first-class serving resource.", intro: "Compare Selected Context with Native Memory at matched quality, then qualify the path that improves latency, throughput, memory, transfer, or reuse.", points: ["Selected Context baseline", "Engine-specific native qualification", "Explicit residency lifecycle", "Quality-adjusted metrics"] },
  "enterprise-ai": { eyebrow: "Enterprise AI", title: "Make context efficiency measurable, reversible, and supportable.", intro: "Start with existing applications and inference endpoints, preserve tenant and authorization boundaries, and qualify each deeper optimization against a frozen baseline.", points: ["Ordinary-text fallback", "No retraining requirement", "Tenant and session isolation", "Reproducible assessment"] },
} as const;

export function SolutionReworkedPage({ slug }: { slug: string }) {
  const copy = solutions[slug as keyof typeof solutions] ?? solutions["long-context"];
  return <><PageHero eyebrow={copy.eyebrow} title={copy.title} intro={copy.intro} actions={<><Link className="button" href="/developers/quickstart">Try PRA <Arrow /></Link><Link className="button button-ghost" href="/products/pra/benchmarks">View evidence</Link></>} /><section className="section wrap"><div className="feature-cards">{copy.points.map((point, index) => <article key={point}><span>{String(index + 1).padStart(2, "0")}</span><h3>{point}</h3></article>)}</div></section><section className="section section-tint"><div className="wrap two-column"><SectionTitle eyebrow="Adoption" title="Start compatible. Promote only with evidence." /><div><p>Use Selected Context through an existing endpoint to establish the workload baseline. Native Memory and Native Serving are measured optimizations, not entry requirements.</p><Link className="inline-link" href="/products/pra/integrations">Choose an engine recommendation <Arrow /></Link></div></div></section><CtaBand /></>;
}
