import Link from "next/link";
import type { Engine } from "@/lib/content";
import { engines } from "@/lib/content";
import { Arrow, Breadcrumbs, CodeBlock, CtaBand, EngineGrid, PageHero, SectionTitle, Status } from "./components";

export function IntegrationsReworkedPage() {
  return <><Breadcrumbs items={[{ label: "PRA", href: "/products/pra" }, { label: "Engine integrations" }]} /><PageHero eyebrow="PRA engine integrations" title="Start compatible. Add native depth only when it wins." intro="Every supported engine can begin with Selected Context. Native Memory and Native Serving are separate, optional qualification paths with engine-specific evidence and fallback." actions={<><Link className="button" href="/products/pra/context">Start with Selected Context <Arrow /></Link><Link className="button button-ghost" href="/products/pra/benchmarks">Benchmark methodology</Link></>} /><section className="section wrap"><div className="integration-legend three"><div><b>Send less</b><span>Selected Context through an existing endpoint</span></div><div><b>Recompute less</b><span>Qualified reusable model-native memory</span></div><div><b>Manage reuse</b><span>Scheduler-owned movement and residency</span></div></div><EngineGrid /></section><section className="section section-tint"><div className="wrap"><SectionTitle eyebrow="Recommendation matrix" title="What should I deploy today?" copy="Compatibility, native mechanism, and serving lifecycle are reported separately. A research mechanism is not presented as a production recommendation." /><div className="table-scroll" role="region" aria-label="Scrollable engine recommendation matrix"><table className="engine-matrix"><thead><tr><th>Engine</th><th>Recommended today</th><th>Selected Context</th><th>Native Memory</th><th>Native Serving</th><th>Evidence</th></tr></thead><tbody>{engines.map((engine) => <tr key={engine.id}><td><Link href={`/products/pra/integrations/${engine.slug}`}>{engine.name}</Link><small>{engine.platform}</small></td><td><strong>{engine.recommendedToday}</strong></td><td>{engine.compatibility}</td><td>{engine.nativeMemory}</td><td>{engine.nativeServing}</td><td><Status>{engine.evidence.status}</Status></td></tr>)}</tbody></table></div><p className="table-note">“Available” means the compatibility path can be evaluated. Native recommendations require the named model, engine, hardware, workload, quality gate, and serving evidence.</p></div></section><CtaBand title="Choose an engine by evidence, not integration depth." /></>;
}

export function EngineReworkedPage({ engine }: { engine: Engine }) {
  const deployment = `existing_application\n  -> PRA_Gateway_or_SDK\n  -> selected_ordinary_context\n  -> ${engine.slug.replaceAll("-", "_")}`;
  return <><Breadcrumbs items={[{ label: "Integrations", href: "/products/pra/integrations" }, { label: engine.name }]} /><PageHero eyebrow={`${engine.category} · ${engine.platform}`} title={`PRA with ${engine.name}`} intro={engine.bestFor} actions={<><Link className="button" href="/company/contact">Discuss this integration <Arrow /></Link><a className="button button-ghost" href={engine.upstream}>Engine documentation</a></>} /><section className="engine-summary"><div className="wrap"><Status>{engine.status}</Status><span>Recommended today: <strong>{engine.recommendedToday}</strong></span><span>Evidence: <strong>{engine.evidence.status}</strong></span></div></section>
  <section className="section wrap"><div className="two-column"><div><SectionTitle eyebrow="1 · What it is used for" title={engine.why} /><ul className="capability-list prominent">{engine.useCases.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="recommendation"><span className="kicker">2 · Recommended PRA deployment today</span><h2>{engine.recommendedToday}</h2><p>{engine.benefit}</p><p className="fallback-note"><strong>Compatibility floor:</strong> selected ordinary context through the existing engine boundary.</p></div></div></section>
  <section className="section section-tint"><div className="wrap two-column"><div><SectionTitle eyebrow="3 · Without engine modification" title="What works now" /><ul className="check-list">{engine.worksWithoutModification.map((item) => <li key={item}>{item}</li>)}</ul></div><div><SectionTitle eyebrow="4 · Native opportunities" title="What deeper integration could unlock" /><ul className="check-list">{engine.nativeOpportunities.map((item) => <li key={item}>{item}</li>)}</ul></div></div></section>
  <section className="section wrap"><SectionTitle eyebrow="5 · Current evidence" title="Evidence belongs to a configuration." /><div className="evidence-record"><div className="evidence-summary"><Status>{engine.evidence.status}</Status><p>{engine.evidence.summary}</p></div><dl><div><dt>Model</dt><dd>{engine.evidence.model}</dd></div><div><dt>Engine</dt><dd>{engine.evidence.engineVersion}</dd></div><div><dt>Hardware</dt><dd>{engine.evidence.hardware}</dd></div><div><dt>Workload</dt><dd>{engine.evidence.workload}</dd></div><div><dt>Provenance</dt><dd>{engine.evidence.provenance}</dd></div><div><dt>Date</dt><dd>{engine.evidence.date}</dd></div></dl><Link className="inline-link" href={engine.evidence.methodology}>Review methodology <Arrow /></Link></div></section>
  <section className="section section-tint"><div className="wrap two-column"><div><SectionTitle eyebrow="6 · Known limitations" title="What is not being claimed" /><ul className="limit-list">{engine.limitations.map((item) => <li key={item}>{item}</li>)}</ul></div><div><SectionTitle eyebrow="7 · Deployment example" title="Begin with the reversible path" /><p>{engine.deploymentExample}</p><CodeBlock>{deployment}</CodeBlock></div></div></section>
  <section className="section wrap"><div className="qualification-grid"><article><span className="kicker">8 · Qualification status</span><h2>{engine.qualification.status}</h2><p><strong>Next gate:</strong> {engine.qualification.nextGate}</p></article><article><span className="kicker">9 · Partner opportunity</span><h2>Build the next evidence row together.</h2><p>{engine.partnerOpportunity}</p><Link className="inline-link" href="/company/contact">Discuss partnership <Arrow /></Link></article></div></section>
  <section className="section section-tint"><div className="wrap"><SectionTitle eyebrow="10 · Technical links" title="Inspect the engine and research context." /><div className="link-stack"><a href={engine.upstream}>Upstream documentation <Arrow /></a><a href={engine.github}>Upstream source <Arrow /></a><a href={engine.paper}>PRA research material <Arrow /></a><Link href="/products/pra/benchmarks">PRA benchmark methodology <Arrow /></Link></div></div></section><CtaBand title={`Benchmark PRA with ${engine.name}.`} /></>;
}
